remote_theme: "mmistakes/so-simple-theme"
locale: "en-us"
title: "Kubernauts.dev"
description: "All things Kubernetes and Developer"
url: "https://kubernauts.dev"
logo: "/images/logo.png"
read_time: true
words_per_minute: 200
