remote_theme: "mmistakes/so-simple-theme"
locale: "en-us"
title: "Kubernauts.dev"
description: "All things Kubernetes and Developer"
url: "https://kubernauts.dev"
logo: "/images/logo.png"
read_time: true
words_per_minute: 200
search_full_content: true
disqus:
  shortname: "kubernauts-dev"
twitter:
 username: "kubernauts_dev"
google_analytics: "UA-75855569-2"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Front Matter Defaults
# defaults:
#   # Post defaults
#   - scope:
#       path: "_posts"
#       type: posts
#     values:
#       layout: post
#       comments: true
#       share: true
#   # Recipe defaults
#   - scope:
#       path: "_recipes"
#       type: recipes
#     values:
#       layout: post
#       comments: true
#       share: true
      
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
